spring:
  application:
    name: service-auth-v1
  profiles:
    active: local
  http:
    encoding:
      force: true
  webflux:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non_empty
    property-naming-strategy: UPPER_CAMEL_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  cloud:
    nacos:
      discovery:
        metadata:
          version: v1
  data:
    mongodb:
      auto-index-creation: true

server:
  http2:
    enabled: true

feign:
  hystrix:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      min-request-size: 204000
  client:
    default-to-properties: true
    config:
      default:
        logger-level: FULL

logging:
  level:
    com.hfhk: debug
