spring:
  profiles:
    active: local
  application:
    name: auth-server-v2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non_empty
    property-naming-strategy: UPPER_CAMEL_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  mvc:
    static-path-pattern: /**
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  data:
    mongodb:
      auto-index-creation: true
  webflux:
    format:
      date: yyyy-MM-dd HH:mm:ss

server:
  http2:
    enabled: true
  max-http-header-size: 16KB
  servlet:
    encoding:
      force: true

logging:
  level:
    root: INFO
    com.hfhk: DEBUG
    org.springframework: info
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    #org.springframework.boot.autoconfigure: DEBUG
