spring:
  application:
    name: auth-server-v2
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non_empty
    property-naming-strategy: UPPER_CAMEL_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  mvc:
    static-path-pattern: /**
  webflux:
    format:
      date: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  data:
    mongodb:
      field-naming-strategy: com.hfhk.cairo.mongo.data.mapping.model.UpperCamelCaseFieldNamingStrategy
      auto-index-creation: true
      database: ${hfhk.mongo.database:hfhk-auth}
      authentication-database: ${hfhk.mongo.authentication-database:hfhk}
      host: ${hfhk.mongo.host:mongo}
      port: ${hfhk.mongo.port:27017}
      username: ${hfhk.mongo.username:hfhk}
      password: ${hfhk.mongo.password:Hfhk.1320.}
  redis:
    database: ${hfhk.redis.database:10}
    host: ${hfhk.redis.host:192.168.30.21}
    port: ${hfhk.redis.port:6379}
    password: ${hfhk.redis.password:Hfhk-!@#-1230.}
    timeout: 10s
    lettuce:
      shutdown-timeout: 5000ms
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  security:
    oauth2:
      client:
        registration:
          wechat-web:
            provider: WECHAT-WEB
            client-name: 微信
            client-id: wxc8e16be9316211a1
            client-secret: b5a161ff99e3088576f0cb37ab34175e
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - snsapi_login
          wechat-open:
            provider: WECHAT-OPEN
            client-name: 微信
            client-id: wx22abd8cc8e58faff
            client-secret: 8b7462a4373e48b00a84ce51ac13534c
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - snsapi_userinfo
          github:
            provider: GITHUB
            client-id: 7e06c0a50323ab314627
            client-secret: 7eb496e52309dfbcfab3862af52610a9377d05bb
            client-name: Github
          google:
            provider: GOOGLE
            client-id: 7e06c0a50323ab314627
            client-secret: 7eb496e52309dfbcfab3862af52610a9377d05bb
            client-name: Google
        provider:
          WECHAT-WEB:
            authorization-uri: https://open.weixin.qq.com/connect/qrconnect?appid=wxc8e16be9316211a1
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-uri: https://api.weixin.qq.com/sns/userinfo
            user-info-authentication-method: form
            user-name-attribute: unionid
          WECHAT-OPEN:
            authorization-uri: https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx22abd8cc8e58faff
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-uri: https://api.weixin.qq.com/sns/userinfo
            user-info-authentication-method: form
            user-name-attribute: unionid


server:
  port: 80
  http2:
    enabled: true
  servlet:
    encoding:
      force: true
  max-http-header-size: 16KB

logging:
  level:
    root: debug
    com.hfhk: debug
    org.springframework: info
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
  file:
    name: /hfhk/auth/server/logs/app.log

hfhk:
  jwks:
    a:
      private: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCF7g5wFVP96kztG//ojU8L97YemUsfd/lcOEXpjuqG0JBMqI+L9ASKmOW3Rk2gsd0ziMhY4+vZX7r5/fSDuUgwPQo0A1BwS0148c+ZG9hR6PXmThTSpeq170t6GCOA17a40cGpm950RtZLUJHeHO6WVZXIc6JdwD2ZLPMT5wEQx426yJVg01ZGqqq50kNP86iTcFCRNJl6p1SnBKr/gii3a/Z/ZhrnQ4fCwBuzW2XZmDH0u9Hi1SbLp9QEPg9ypbM6V82BjwSfYEZtv7kdyEE78yPjGGNP9vEM4lLJYD0T6mJvxVkGrV+ibE2CHTVFFRzcEjM4qDa7qQ/c/PHNZjVdAgMBAAECggEAPnpwl88LUL+1xUMzndwWDSIw/pNKnVKNrHy/+JXoSJ4RQwG7fXGHkNSFDXupiRaQd5MOy5EAHHbxNeBH6g9MYtyG3v7QzqICcTJ1QxrfTk7cL+UrB53JIbiRQFL0dQ2suwl3S9Vf8GR/YcEjWzeqAc3JQyrWit+8nLGAcD9qmtWcKDKOyZASlHCIp5xDlWsz4u32mUuZsg6+l0QjbzkJRNMJNLaAHPUVD4b14kYONVImg+YlWGcquxTmamOuPAKsq2H2levdnUZA2wsGSI0DtqRmjUaPzHP3UR+4ELROauBtIc8HrvO6jy7JkBaCqNj9voMSL77qWaKztwy7Lb3BoQKBgQDmHFWkJnY5wQHnMtnqUg5dBMGpI1ATANS+lUd3A3WLsyAyE0PoM5jDzAh9+9tepoQ6U6GdImxmGql0UdovIlHCyfwxL/yhAaJ46Qq1hwc7gug+zYpd0Cjv5qJLMzLefZIszgUjt21TQnlI39oqi1qfZYWoRLW4KcYRGu9sb97OVQKBgQCU/4QOwozFiPDOx6Wd5i8ap9Qt3tTZsY+GzfNFyrFH0Y8Y+IH7nACPJ+10H8hv8HKlj6nVPW/Ackv1JJPRLWDJZKvx/wow9txSoLvefWngzq/VHmvXM9wkBhzZ9NgCj+PV/SdMJNxO+B2/7Dk41bceeJOwFQV1mOt/5QqhVkDC6QKBgBOtMJWMxGdD3cnLS18CDUBe+8BeyKYXWBnD4gyHOzHq60Hc692bK+DyPXeoZaW+T2g9ZoBtRR+l//92UFXfdWZWpz39gHi0DxSPuN604SVxmDJmmQJUnmuFKTOM+TiVPD6gj0fyk2KfOIfGvH0O1XzzzW4KEg/hYpJr3zVCi6bRAoGAPDWAtMIzRoOO49BTgZoJwNi+6gZYttuEpzHEM5izyNTK4YlSZU1mAHNfBgTt5yYf/f0u4Oehp//H5/ju7qFKsjdHMFQiVyT6ZT1kjYTaayi6bwGLDHx9YeVCdWT2gRqKM+fHoIJosFSdGPgpK2lZRSvuakIkYZ/40kbI4+dJ5jkCgYEA1ERAmaidhsrAD5xm2JuMXFUXMY361CurL4iFZQNJ3GyDBzbyi3NCxNIQlLaxxNkuq//t3jjU7qeze2RYx9i/SBuwpNNetPwyg6nGTimaqlCZngLJAqPbX8GL8ha+3+4Gj1hN0T5WOdf/WcA/8IEQj7P2GPAIdSCgqQsJQqIfRcQ=
      public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhe4OcBVT/epM7Rv/6I1PC/e2HplLH3f5XDhF6Y7qhtCQTKiPi/QEipjlt0ZNoLHdM4jIWOPr2V+6+f30g7lIMD0KNANQcEtNePHPmRvYUej15k4U0qXqte9LehgjgNe2uNHBqZvedEbWS1CR3hzullWVyHOiXcA9mSzzE+cBEMeNusiVYNNWRqqqudJDT/Ook3BQkTSZeqdUpwSq/4Iot2v2f2Ya50OHwsAbs1tl2Zgx9LvR4tUmy6fUBD4PcqWzOlfNgY8En2BGbb+5HchBO/Mj4xhjT/bxDOJSyWA9E+pib8VZBq1fomxNgh01RRUc3BIzOKg2u6kP3PzxzWY1XQIDAQAB
