server:
  port: 80

spring:
  data:
    mongodb:
      host: 192.168.30.21
      port: 27017
      username: harpoon
      password: Hfhk-harpoon-!@#-1230.
      authentication-database: harpoon-auth
      database: harpoon-auth
