spring:
  application:
    name: auth-server-v2
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non_empty
    property-naming-strategy: UPPER_CAMEL_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  mvc:
    static-path-pattern: /**
  webflux:
    format:
      date: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  data:
    mongodb:
      field-naming-strategy: com.hfhk.cairo.mongo.data.mapping.model.UpperCamelCaseFieldNamingStrategy
      auto-index-creation: true
      database: ${hfhk.mongo.database:hfhk-auth}
      authentication-database: ${hfhk.mongo.authentication-database:hfhk}
      host: ${hfhk.mongo.host:mongo}
      port: ${hfhk.mongo.port:27017}
      username: ${hfhk.mongo.username:hfhk}
      password: ${hfhk.mongo.password:Hfhk.1320.}
  security:
    oauth2:
      client:
        registration:
          wechat-web:
            provider: WECHAT-WEB
            client-name: 微信
            client-id: wxc8e16be9316211a1
            client-secret: b5a161ff99e3088576f0cb37ab34175e
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - snsapi_login
          github:
            provider: GITHUB
            client-id: 7e06c0a50323ab314627
            client-secret: 7eb496e52309dfbcfab3862af52610a9377d05bb
            client-name: Github
          google:
            provider: GOOGLE
            client-id: 7e06c0a50323ab314627
            client-secret: 7eb496e52309dfbcfab3862af52610a9377d05bb
            client-name: Google
        provider:
          WECHAT-WEB:
            authorization-uri: https://open.weixin.qq.com/connect/qrconnect?appid=wxc8e16be9316211a1
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token?appid=wxc8e16be9316211a1
            user-info-uri: https://api.weixin.qq.com/sns/userinfo
            user-name-attribute: unionid

server:
  port: 80
  http2:
    enabled: true
  servlet:
    encoding:
      force: true
  max-http-header-size: 16KB

logging:
  level:
    root: debug
    com.hfhk: debug
    org.springframework: info
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
  file:
    name: /hfhk/auth/server/logs/app.log
