hfhk:
  mongo:
    database: hfhk-auth
    authentication-database: hfhk
    host: 192.168.30.21
    port: 27017
    username: hfhk
    password: Hfhk.1320.
#  redis:
#    database: 11
#    host: 192.168.30.21
#    port: 6379
#    password: Hfhk-!@#-1230.
