spring:
  application:
    name: auth-server-v2
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non_empty
    property-naming-strategy: UPPER_CAMEL_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  mvc:
    static-path-pattern: /**

  webflux:
    format:
      date: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  data:
    mongodb:
      field-naming-strategy: com.hfhk.cairo.mongo.data.mapping.model.UpperCamelCaseFieldNamingStrategy
      auto-index-creation: true
      database: ${hfhk.mongo.database:hfhk-auth}
      authentication-database: ${hfhk.mongo.authentication-database:hfhk}
      host: ${hfhk.mongo.host:mongo}
      port: ${hfhk.mongo.port:27017}
      username: ${hfhk.mongo.username:hfhk}
      password: ${hfhk.mongo.password:Hfhk.1320.}

server:
  port: 80
  http2:
    enabled: true
  servlet:
    encoding:
      force: true
  max-http-header-size: 16KB

logging:
  level:
    root: debug
    com.hfhk: debug
    org.springframework: info
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
  file:
    name: /hfhk/auth/server/logs/app.log
