version: '3.7'

networks:
  default:
    name: cairo

services:
  redis:
    image: redis:6.2.1-alpine
    stdin_open: true
    tty: true
    entrypoint: redis-server /etc/redis/redis.conf
    volumes:
      - /hfhk/redis/conf:/etc/redis
      - /hfhk/redis/data:/data
    networks:
      default: { }
    logging:
      driver: 'json-file'
      options:
        max-size: 100M
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      resources:
        limits:
          # cpus: '4'
          memory: 2G
        reservations:
          # cpus: '4'
          memory: 1G
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 10
        delay: 3s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 3s
        order: stop-first
    ports:
      - 6379:6379
  mongo:
    image: mongo:4.4.4

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1320.
    volumes:
      - /hfhk/mongo/data:/data/db
    networks:
      default: { }
    ports:
      - 27017:27017
    tty: true
    stdin_open: true
    logging:
      driver: 'json-file'
      options:
        max-size: 100M
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      resources:
        limits:
          #cpus: '4'
          memory: 2G
        reservations:
          #cpus: '4'
          memory: 1G
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 10
        delay: 3s
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 3s
        order: stop-first
  consul:
    image: consul:1.9.1
    command: agent -server -client=0.0.0.0 -node=consul -datacenter=hfhk -ui -dev
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      default:
        aliases:
          - consul
    ports:
      - 8500:8500
    logging:
      driver: 'json-file'
      options:
        max-size: 100M
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  auth_server:
    image: registry.cn-beijing.aliyuncs.com/hfhksoft/auth-server:snapshot
    hostname: auth_server
    environment:
      HFHK_MONGO_DABASE: hfhk-auth
      HFHK_MONGO_DATBASE: hfhk-auth
      HFHK_MONGO_AUTHENTICATION-DATABASE: hfhk
      HFHK_MONGO_HOST: 192.168.30.21
      HFHK_MONGO_PORT: 27017
      HFHK_MONGO_USERNAME: hfhk
      HFHK_MONGO_PASSWORD: Hfhk.1320.

    networks:
      default:
        aliases:
          - auth-server
    ports:
      - 7822:80
    tty: true
    stdin_open: true
    logging:
      driver: 'json-file'
      options:
        max-size: 100M
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  auth_server2:
    image: registry.cn-beijing.aliyuncs.com/hfhksoft/lijiajia3515-cairo-auth-server:2021.3.1
    hostname: auth_server2
    environment:
      LIJIAJIA3515_MONGO_DATABASE: lijiajia3515-auth
      LIJIAJIA3515_MONGO_AUTHENTICATION-DATABASE: lijiajia3515
      LIJIAJIA3515_MONGO_AUTHENTICATIONDATABASE: lijiajia3515
      LIJIAJIA3515_MONGO_HOST: mongo
      LIJIAJIA3515_MONGO_PORT: 27017
      LIJIAJIA3515_MONGO_USERNAME: lijiajia3515
      LIJIAJIA3515_MONGO_PASSWORD: lijiajia3515

      LIJIAJIA3515_REDIS_DATABASE: 0
      LIJIAJIA3515_REDIS_HOST: redis
      LIJIAJIA3515_REDIS_PORT: 6379
      LIJIAJIA3515_REDIS_USERNAME: lijiajia3515
      LIJIAJIA3515_REDIS_PASSWORD: lijiajia3515

    networks:
      default:
        aliases:
          - auth-server2
    ports:
      - 7823:80
    depends_on:
      - mongo
      - redis
      - consul
    tty: true
    stdin_open: true
    logging:
      driver: 'json-file'
      options:
        max-size: 100M
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  auth_service:
    image: registry.cn-beijing.aliyuncs.com/hfhksoft/auth-service:snapshot
    environment:
      HFHK_MONGO_DATABASE: hfhk-auth
      HFHK_MONGO_AUTHENTICATION-DATABASE: hfhk
      HFHK_MONGO_HOST: 192.168.30.21
      HFHK_MONGO_PORT: 27017
      HFHK_MONGO_USERNAME: hfhk
      HFHK_MONGO_PASSWORD: Hfhk.1320.
      HFHK_CONSUL_HOST: consul
      HFHK_CONSUL_PORT: 8500
      HFHK_CONSUL_DISCOVERY_INSTANCE-ZONE: hfhk
      HFHK_CONSUL_DISCOVERY_INSTANCE-GROUP: hfhk
      HFHK_AUTH_SERVER: auth-server
      HFHK_AUTH_CLIENT_ID: hfhk_auth
      HFHK_AUTH_CLIENT_SECRET: hfhk_auth

      SPRING_CLOUD_CONSUL_DISCOVERY_IPADDRESS: 192.168.30.22
      SPRING_CLOUD_CONSUL_DISCOVERY_PORT: 10000
    depends_on:
      - consul
      - auth_server
    networks:
      default: { }
    ports:
      - 10000:80
    tty: true
    stdin_open: true
    logging:
      driver: 'json-file'
      options:
        max-size: 100M
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  system_service:
    image: registry.cn-beijing.aliyuncs.com/hfhksoft/system-service:snapshot
    environment:
      HFHK_MONGO_DATABASE: hfhk-system
      HFHK_MONGO_GRIDFS_DATABASE: hfhk-system
      HFHK_MONGO_GRIDFS_BUCKET: hfhk
      HFHK_MONGO_AUTHENTICATION-DATABASE: hfhk
      HFHK_MONGO_HOST: 192.168.30.21
      HFHK_MONGO_PORT: 27017
      HFHK_MONGO_USERNAME: hfhk
      HFHK_MONGO_PASSWORD: Hfhk.1320.
      HFHK_CONSUL_HOST: consul
      HFHK_CONSUL_PORT: 8500
      HFHK_CONSUL_DISCOVERY_INSTANCE-ZONE: hfhk
      HFHK_CONSUL_DISCOVERY_INSTANCE-GROUP: hfhk
      HFHK_AUTH_SERVER: auth-server
      HFHK_AUTH_CLIENT_ID: hfhk_system
      HFHK_AUTH_CLIENT_SECRET: hfhk_system

      SPRING_CLOUD_CONSUL_DISCOVERY_IPADDRESS: 192.168.30.22
      SPRING_CLOUD_CONSUL_DISCOVERY_PORT: 10010
    depends_on:
      - consul
      - auth_service
      - auth_server
    networks:
      default: { }
    ports:
      - 10010:80
    tty: true
    stdin_open: true
    logging:
      driver: 'json-file'
      options:
        max-size: 100M
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  check_service:
    image: registry.cn-beijing.aliyuncs.com/hfhksoft/check-service:snapshot
    environment:
      HFHK_MONGO_DATABASE: hfhk-check
      HFHK_MONGO_GRIDFS_DATABASE: hfhk-check
      HFHK_MONGO_GRIDFS_BUCKET: hfhk
      HFHK_MONGO_AUTHENTICATION-DATABASE: hfhk
      HFHK_MONGO_HOST: 192.168.30.21
      HFHK_MONGO_PORT: 27017
      HFHK_MONGO_USERNAME: hfhk
      HFHK_MONGO_PASSWORD: Hfhk.1320.
      HFHK_CONSUL_HOST: consul
      HFHK_CONSUL_PORT: 8500
      HFHK_CONSUL_DISCOVERY_INSTANCE-ZONE: hfhk
      HFHK_CONSUL_DISCOVERY_INSTANCE-GROUP: hfhk
      HFHK_AUTH_SERVER: auth-server
      HFHK_AUTH_CLIENT_ID: hfhk_check
      HFHK_AUTH_CLIENT_SECRET: hfhk_check

      SPRING_CLOUD_CONSUL_DISCOVERY_IPADDRESS: 192.168.30.22
      SPRING_CLOUD_CONSUL_DISCOVERY_PORT: 10020
    depends_on:
      - consul
      - auth_service
      - auth_server
    tty: true
    stdin_open: true
    logging:
      driver: 'json-file'
      options:
        max-size: 100M
    networks:
      default: { }
    ports:
      - 10020:80
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  cb_service:
    image: registry.cn-beijing.aliyuncs.com/hfhksoft/cb-service:snapshot
    environment:
      HFHK_MONGO_DATABASE: hfhk-cb
      HFHK_MONGO_GRIDFS_DATABASE: hfhk-cb
      HFHK_MONGO_GRIDFS_BUCKET: hfhk
      HFHK_MONGO_AUTHENTICATION-DATABASE: hfhk
      HFHK_MONGO_HOST: 192.168.30.21
      HFHK_MONGO_PORT: 27017
      HFHK_MONGO_USERNAME: hfhk
      HFHK_MONGO_PASSWORD: Hfhk.1320.
      HFHK_CONSUL_HOST: consul
      HFHK_CONSUL_PORT: 8500
      HFHK_CONSUL_DISCOVERY_INSTANCE-ZONE: hfhk
      HFHK_CONSUL_DISCOVERY_INSTANCE-GROUP: hfhk
      HFHK_AUTH_SERVER: auth-server
      HFHK_AUTH_CLIENT_ID: hfhk_dhgxjsj
      HFHK_AUTH_CLIENT_SECRET: hfhk_dhgxjsj

      SPRING_CLOUD_CONSUL_DISCOVERY_IPADDRESS: 192.168.30.22
      SPRING_CLOUD_CONSUL_DISCOVERY_PORT: 10030
    depends_on:
      - consul
      - auth_server
    networks:
      default: { }
    ports:
      - 10030:80
    tty: true
    stdin_open: true
    logging:
      driver: 'json-file'
      options:
        max-size: 100M
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first

  gateway:
    image: registry.cn-beijing.aliyuncs.com/hfhksoft/gateway:cb-snapshot
    environment:
      HFHK_CONSUL_HOST: consul
      HFHK_CONSUL_PORT: 8500
      HFHK_CONSUL_DISCOVERY_INSTANCE-ZONE: hfhk
      HFHK_CONSUL_DISCOVERY_INSTANCE_GROUP: hfhk
    depends_on:
      - consul
      - auth_service
      - system_service
      - check_service
      - cb_service
    networks:
      default: { }
    ports:
      - 81:80
    tty: true
    stdin_open: true
    logging:
      driver: 'json-file'
      options:
        max-size: 100M
    healthcheck: { }
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  cb_management:
    image: registry.cn-beijing.aliyuncs.com/hfhksoft/cb-management:snapshot
    environment:
      TZ: Asia/Shanghai
    networks:
      default: { }
    ports:
      - 8888:80
    depends_on:
      - auth_server
      - gateway
    tty: true
    stdin_open: true
    logging:
      driver: 'json-file'
      options:
        max-size: 100M
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  nginx:
    image: nginx:stable
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /hfhk/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:r
      - /hfhk/nginx/conf/conf.d:/etc/nginx/conf.d:r
      - /hfhk/nginx/share:/usr/share/nginx
      - /hfhk/nginx/logs:/var/log/nginx
    networks:
      default: { }
    ports:
      - 80:80
      - 443:443
    depends_on:
      - auth_server
      - gateway
    tty: true
    stdin_open: true
    logging:
      driver: 'json-file'
      options:
        max-size: 100M
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

