version: '3.7'

networks:
  default:
    name: cairo

services:
  consul:
    image: consul:1.9.1
    hostname: consul
    #command: sh
    command: agent -server -client=0.0.0.0 -node=consul -datacenter=hfhk -ui -dev
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      default:
        aliases:
          - consul
    ports:
      - 8500:8500
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  auth_server:
    image: registry.cn-beijing.aliyuncs.com/hfhksoft/auth-server:snapshot
    hostname: auth_server
    environment:
      HFHK_MONGO_DABASE: hfhk-auth
      HFHK_MONGO_AUTHENTICATION-DATABASE: hfhk
      HFHK_MONGO_HOST: 192.168.30.21
      HFHK_MONGO_PORT: 27017
      HFHK_MONGO_USERNAME: hfhk
      HFHK_MONGO_PASSWORD: Hfhk.1320.
    tty: true
    stdin_open: true
    networks:
      default:
        aliases:
          - auth-server
    ports:
      - 10000:80
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  auth_service:
    image: registry.cn-beijing.aliyuncs.com/hfhksoft/auth-service:snapshot
    environment:
      HFHK_MONGO_DATABASE: hfhk-auth
      HFHK_MONGO_AUTHENTICATION-DATABASE: hfhk
      HFHK_MONGO_HOST: 192.168.30.21
      HFHK_MONGO_PORT: 27017
      HFHK_MONGO_USERNAME: hfhk
      HFHK_MONGO_PASSWORD: Hfhk.1320.
      HFHK_CONSUL_HOST: consul
      HFHK_CONSUL_PORT: 8500
      HFHK_CONSUL_DISCOVERY_INSTANCE-ZONE: hfhk
      HFHK_CONSUL_DISCOVERY_INSTANCE-GROUP: hfhk
      HFHK_AUTH_SERVER: auth-server
      HFHK_AUTH_CLIENT_ID: hfhk_auth
      HFHK_AUTH_CLIENT_SECRET: hfhk_auth
    depends_on:
      - consul
      - auth_server
    tty: true
    stdin_open: true
    networks:
      default: { }
    ports: [ ]
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  gateway:
    image: registry.cn-beijing.aliyuncs.com/hfhksoft/gateway:v1-snapshot
    environment:
      HFHK_CONSUL_HOST: consul
      HFHK_CONSUL_PORT: 8500
      HFHK_CONSUL_DISCOVERY_INSTANCE-ZONE: hfhk
      HFHK_CONSUL_DISCOVERY_INSTANCE_GROUP: hfhk
    depends_on:
      - consul
      - auth_service
    tty: true
    stdin_open: true
    healthcheck:
      disable: true
    networks:
      default: { }
    ports: [ ]
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  nginx:
    image: nginx:stable
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /hfhk/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:r
      - /hfhk/nginx/conf/conf.d:/etc/nginx/conf.d:r
      - /hfhk/nginx/share:/usr/share/nginx
      - /hfhk/nginx/logs:/var/log/nginx
    networks:
      default: { }
    ports:
      - 80:80
      - 443:443
    depends_on:
      - auth_server
      - gateway
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
