hfhk:
  auth:
    server: localhost
    client:
      id: hfhk_auth
      secret: hfhk_auth
  mongo:
    database: hfhk-auth
    gridfs:
      database: hfhk-auth
      bucket: hfhk
    authentication-database: hfhk
    host: 192.168.30.21
    port: 27017
    username: hfhk
    password: Hfhk.1320.
  redis:
    database: 10
    host: 192.168.30.21
    port: 6379
    password: Hfhk-!@#-1230.
  consul:
    host: 192.168.30.22
    port: 8500
    discovery:
      instance-zone: local
      instance-group: local

server:
  port: 10000
