feign:
  hystrix:
    enabled: false
  okhttp:
    enabled: true
  httpclient:
    connection-timeout: 60000
  compression:
    request:
      min-request-size: 204000
  client:
    default-to-properties: true
    config:
      default:
        logger-level: FULL
