hfhk:
  auth:
    server: auth.hfhksoft.com
    client:
      id: hfhk_auth
      secret: hfhk_auth
  nacos:
    server-addr: 192.168.30.21:8848
    discovery:
      server_addr: 192.168.30.21:8848
      namespace: hfhk
      group: hfhk
  consul:
    host: 192.168.30.21
    port: 8500
    discovery:
      instance-zone: hfhk
      instance-group: hfhk

server:
  port: 10000
