hfhk:
  auth:
    server: auth.hfhksoft.com
    client:
      id: hfhk_auth
      secret: hfhk_auth
  consul:
    host: 192.168.30.22
    port: 8500
    discovery:
      instance-zone: hfhk
      instance-group: hfhk

server:
  port: 10000
