spring:
  application:
    name: service-auth-v1
  profiles:
    active:
      - local
  web:
    locale: zh_CN
  webflux:
    format:
      date: yyyy-MM-dd HH:mm:ss
  session:
    timeout: 7D
    store-type: none
    mongodb:
      collection-name: sessions
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non_empty
    property-naming-strategy: UPPER_CAMEL_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://${lijiajia3515.auth.server}
        registration:
          lijiajia3515_test:
            provider: spring
            client-id: lijiajia3515_test
            client-secret: lijiajia3515_test
            client-name: 测试
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
          lijiajia3515_test2:
            provider: spring
            client-id: lijiajia3515_test2
            client-secret: lijiajia3515_test2
            client-name: 测试2
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
          lijiajia3515_dhgxjsj:
            provider: spring
            client-id: lijiajia3515_dhgxjsj
            client-secret: lijiajia3515_dhgxjsj
            client-name: 东湖高新建设局
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
          lijiajia3515-common-check-client-credentials:
            provider: spring
            client-id: lijiajia3515_common_check
            client-secret: lijiajia3515_client_common_check
            client-name: 浩方恒科-客户端-检查服务
            authorization-grant-type: client_credentials
            scope:
              - message.read
              - message.write
      resourceserver:
        jwt:
          jwk-set-uri: http://${lijiajia3515.auth.server}/oauth2/jwks

security:
  oauth2:
    client:
      id: ${random.value}
      client-id: ${lijiajia3515.auth.client.id:lijiajia3515_auth}
      client-secret: ${lijiajia3515.auth.client.id:lijiajia3515_auth}
      grant-type: client_credentials
      access-token-uri: http://${lijiajia3515.auth.server:auth-server}/oauth2/token


feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    connection-timeout: 60000
  compression:
    request:
      min-request-size: 204000
  client:
    default-to-properties: true
    config:
      client:
        default-to-properties: true
        config:
          default:
            logger-level: FULL

          serviceAuthV1-auth-basic-client:
            logger-level: FULL
            request-interceptors:
              - com.lijiajia3515.cairo.feign.interceptor.BasicRequestInterceptor
          serviceAuthV1-user-clientCredentials-client:
            logger-level: FULL
            request-interceptors:
              - com.lijiajia3515.cairo.feign.interceptor.ClientOAuth2RequestInterceptor
              -
          serviceSystemV1-file-request-client:
            logger-level: FULL
            request-interceptors:
              - com.lijiajia3515.cairo.feign.interceptor.RequestOAuth2RequestInterceptor
          serviceSystemV1-file-clientCredentials-client:
            logger-level: FULL
            request-interceptors:
              - com.lijiajia3515.cairo.feign.interceptor.ClientOAuth2RequestInterceptor
          serviceSystemV1-dictionary-clientCredentials-client:
            logger-level: FULL
            request-interceptors:
              - com.lijiajia3515.cairo.feign.interceptor.ClientOAuth2RequestInterceptor

server:
  port: 80
  http2:
    enabled: true
  servlet:
    encoding:
      force: true

logging:
  level:
    root: info
    com.lijiajia3515: debug
  file:
    name: /lijiajia3515/demo/logs/lijiajia3515.log

management:
  endpoints:
    web:
      exposure:
        include: "*"

