spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  web:
    locale: zh_CN
  webflux:
    format:
      date: yyyy-MM-dd HH:mm:ss
  session:
    timeout: 7D
    store-type: none
    mongodb:
      collection-name: sessions
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non_empty
    property-naming-strategy: UPPER_CAMEL_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false


server:
  port: 80
  http2:
    enabled: true
  servlet:
    encoding:
      force: true

logging:
  level:
    root: info
    com.hfhk: debug
  file:
    name: /hfhk/demo/logs/hfhk.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
