spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME:harpoon}
      password: ${MONGO_PASSWORD:Hfhk-HARPOON_!@#-1230.}
      database: ${MONGO_DATABSE:harpoon}
      authentication-database: ${MONGO_AUTHENTICATION_DATABSE:harpoon}
      auto-index-creation: true

  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      discovery:
        server-addr: ${NACOS_DISCOVERY_SERVER_ADDR:${NACOS_SERVER_ADDR:localhost:8848}}
        namespace: ${NACOS_DISCOVERY_NAMESPACE:${NACOS_NAMESPACE:harpoon}}
        group: ${NACOS_DISCOVERY_GROUP:${NACOS_GROUP:harpoon}}
      # config:
      #   server-addr: ${NACOS_CONFIG_SERVER_ADDR:${NACOS_SERVER_ADDR:localhost:8848}}
      #   namespace: ${NACOS_CONFIG_NAMESPACE:${NACOS_NAMESPACE:harpoon}}
      #   group: ${NACOS_CONFIG_GROUP:${NACOS_GROUP:harpoon}}
      #   file-extension: yaml


security:
  oauth2:
    authorization:
      jwt:
        key-store: ${HARPOON_JWT_KEY_STORE:classpath:cairo.p12}
        key-store-password: ${HARPOON_JWT_STORE_PASSWORD:harpoon}
        key-alias: ${HARPOON_JWT_KEY_ALIAS:harpoon}
        key-password: ${HARPOON_JWT_KEY_PASSWORD:harpoon}

server:
  port: 80
  max-http-header-size: 102400000

harpoon:
  oauth2:
    authorization:
      jwt:
        key-store: ${HARPOON_JWT_KEY_STORE:classpath:cairo.p12}
        key-store-password: ${HARPOON_JWT_STORE_PASSWORD:harpoon}
        key-alias: ${HARPOON_JWT_KEY_ALIAS:harpoon}
        key-password: ${HARPOON_JWT_KEY_PASSWORD:harpoon}

logging:
  level:
    root: info
    com.hfhk.harpoon: debug
  file:
    name: /hfhk/cairo/auth/server/logs/app.log
