server:
  port: 10000

spring:
  data:
    mongodb:
      host: 192.168.30.21
      port: 27017
      username: cairo
      password: Hfhk-cairo-!@#-1230.
      authentication-database: cairo
      database: cairo-auth
  cloud:
    nacos:
      # config:
      #   server-addr: 192.168.30.21:8848
      #   namespace: local
      #   group: local
      #   file-extension: yaml
      discovery:
        server-addr: 192.168.30.21:8848
        namespace: local
        group: local

security:
  oauth2:
    authorization:
      jwt:
        key-store: classpath:cairo.p12
        key-store-password: harpoon
        key-alias: harpoon
        key-password: harpoon

harpoon:
  oauth2:
    authorization:
      jwt:
        key-store: classpath:cairo.p12
        key-store-password: harpoon
        key-alias: harpoon
        key-password: harpoon

logging:
  level:
    com.hf.harpoon: debug
  file:
    name: /hfhk/cairo/auth/server/app.log
