lijiajia3515:
  mongo:
    database: lijiajia3515-auth
    authentication-database: lijiajia3515
    host: 192.168.30.22
    port: 27017
    username: lijiajia3515
    password: lijiajia3515
  redis:
    database: 0
    host: 192.168.30.22
    port: 6379
    username: lijiajia3515
    password: lijiajia3515
