lijiajia3515:
  workdir: /hfhk/auth/server
  mongo:
    database: hfhk-auth
    authentication-database: hfhk
    host: 192.168.30.22
    port: 27017
    username: hfhk
    password: Hfhk.1320.
  redis:
    database: 1
    host: 192.168.30.22
    port: 6379
    username: hfhk
    password: Hfhk.1320.
