spring:
  application:
    name: service-auth-v2
  profiles:
    active:
      - local
  web:
    locale: zh_CN
  webflux:
    format:
      date: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non_empty
    property-naming-strategy: UPPER_CAMEL_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  session:
    timeout: 30D
    store-type: redis
    redis:
      namespace: ${spring.application.name}:session
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${lijiajia3515.auth.server:auth-server}/oauth2/jwks
  data:
    mongodb:
      auto-index-creation: true
      field-naming-strategy: com.lijiajia3515.cairo.mongo.data.mapping.model.UpperCamelCaseFieldNamingStrategy
      database: ${lijiajia3515.mongo.database:lijiajia3515-auth}
      gridfs:
        database: ${lijiajia3515.mongo.gridfs.database:lijiajia3515-auth}
      host: ${lijiajia3515.mongo.host:mongo}
      port: ${lijiajia3515.mongo.port:27017}
      username: ${lijiajia3515.mongo.username:lijiajia3515}
      password: ${lijiajia3515.mongo.password:lijiajia3515.1320.}
      authentication-database: ${lijiajia3515.mongo.authentication-database:lijiajia3515}
  redis:
    database: ${lijiajia3515.redis.database:0}
    host: ${lijiajia3515.redis.host:redis}
    port: ${lijiajia3515.redis.port:6379}
    username: ${lijiajia3515.redis.username:default}
    password: ${lijiajia3515.redis.password:1320.1320.}
    timeout: 10s
    lettuce:
      shutdown-timeout: 5000ms
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  cloud:
    consul:
      host: ${lijiajia3515.consul.host:localhost}
      port: ${lijiajia3515.consul.port:8500}
      discovery:
        prefer-ip-address: true
        health-check-interval: 5s
        instance-zone: ${lijiajia3515.consul.discovery.instance-zone:lijiajia3515}
        instance-group: ${lijiajia3515.consul.discovery.instance-group:lijiajia3515}
        tags:
          - v1
server:
  port: 80
  max-http-header-size: 8KB
  http2:
    enabled: true
  servlet:
    application-display-name: ${spring.application.name}
    encoding:
      force: true
    session:
      cookie:
        name: cairo
        path: /
        comment: token


feign:
  okhttp:
    enabled: true
  httpclient:
    connection-timeout: 60000
  compression:
    request:
      min-request-size: 204000
  client:
    default-to-properties: true
    config:
      client:
        default-to-properties: true
        config:
          default:
            logger-level: FULL
          authenticationClient:
            logger-level: FULL
            request-interceptors:
              - com.lijiajia3515.cairo.feign.interceptor.BasicRequestInterceptor
          userV1Client:
            logger-level: FULL
            request-interceptors:
              - org.springframework.cloud.openfeign.security.OAuth2FeignRequestInterceptor
          serviceAuthV1-user-clientCredentials-client:
            logger-level: FULL
            request-interceptors:
              - com.lijiajia3515.cairo.feign.interceptor.ClientOAuth2RequestInterceptor
          serviceSystemV1-file-request-client:
            logger-level: FULL
            request-interceptors:
              - com.lijiajia3515.cairo.feign.interceptor.RequestOAuth2RequestInterceptor
          serviceSystemV1-file-clientCredentials-client:
            logger-level: FULL
            request-interceptors:
              - com.lijiajia3515.cairo.feign.interceptor.ClientOAuth2RequestInterceptor
          serviceSystemV1-dictionary-clientCredentials-client:
            logger-level: FULL
            request-interceptors:
              - com.lijiajia3515.cairo.feign.interceptor.ClientOAuth2RequestInterceptor


management:
  endpoints:
    web:
      exposure:
        include:
          - '*'


logging:
  level:
    root: info
    com.lijiajia3515: debug
  file:
    name: /lijiajia3515/auth/service/logs/app.log

lijiajia3515:
  auth:
    server: http://auth.hfhksoft.com
